"""
Script for cleaning paper CSV file.
Script for generating individual paper pages.

NOTE: raw_papers.txt must be generated by exporting from Excel in "UTF-16 Unicode Text (.txt)".
This resolves an assortment of encoding issues for Latin-1 characters.

python3 _data/scripts/papers.py raw_papers.txt _data/papers.csv
"""

import argparse
import codecs
import csv
import os

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('tsv_infile')
    parser.add_argument('csv_outfile')
    parser.add_argument('outdir')
    args = parser.parse_args()

    os.makedirs(args.outdir, exist_ok=True)

    # Read raw paper information
    with codecs.open(args.tsv_infile, 'r', 'utf16') as f:
        reader = csv.DictReader(f, delimiter='\t')
        raw_paper_data = sorted(reader,
            key=lambda d: d['Paper Title'].replace('(', '').lower())

    # Generate paper CSV and pages
    with open(args.csv_outfile, 'w') as f:
        writer = csv.DictWriter(f, fieldnames=[
            'session_id', 'external_id', 'internal_id',
            'title', 'abstract', 'authors', 'areas'])

        writer.writeheader()
        for i, raw_paper in enumerate(raw_paper_data, 1):
            abstract = raw_paper['Abstract'].encode('ascii', 'xmlcharrefreplace').decode()
            authors = ', '.join([
                ' '.join(author.split(',')[0].replace('*', '').split())
                for author in raw_paper['Author Names'].encode('ascii', 'xmlcharrefreplace').decode().split('; ')
            ])

            paper = {
                'session_id': 0,
                'external_id': '{:0>2}'.format(i),
                'internal_id': raw_paper['Paper ID'],
                'title': raw_paper['Paper Title'],
                'abstract': abstract,
                'authors': authors,
                'areas': raw_paper['Subject Areas'],
            }

            # Write row to CSV
            writer.writerow(paper)

            front_matter = [
                '-' * 3,
                'layout: page',
                'title: "{}"'.format(paper['title']),
                'comments: true',
                'invisible: true',
                '-' * 3,
            ]
            data = [
                'Authors: {authors}'.format(authors=paper['authors']),
            ]
            formatted_data = ['<p class="text-left"><i>{}</i></p>'.format(d) for d in data]

            # Generate page
            outpath = os.path.join(args.outdir,  '{id}.md'.format(id=paper['external_id']))
            with open(outpath, 'w') as fout:
                page_data = [
                    '\n'.join(front_matter),
                    '\n'.join(formatted_data),
                    paper['abstract'],
                    '{% include disqus.html %}'
                ]
                fout.write('\n\n'.join(page_data))

if __name__ == '__main__':
    main()    
